import test from 'node:test';
import assert from 'node:assert/strict';
import { mkdtempSync, readFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { once } from 'node:events';
import { DatabaseSync } from 'node:sqlite';
import { openStore, hashPassword } from '../server/store.mjs';
import { createApplication } from '../server/api.mjs';
import { seedDemo } from '../scripts/seed-demo.mjs';

test('demo replacement preserves accounts/custom works and creates usable, private application records', async t => {
  const dir = mkdtempSync(join(tmpdir(), 'sapatri-demo-'));
  const dbPath = join(dir, 'test.sqlite'), outputPath = join(dir, 'public.json');
  let app;
  t.after(async () => {
    if (app) { app.server.closeAllConnections(); await new Promise(r => app.server.close(r)); app.db.close(); }
    rmSync(dir, { recursive: true, force: true });
  });
  let db = openStore(dbPath);
  const hash = await hashPassword('Preserved-Password-2026!');
  db.prepare('INSERT INTO users(id,name,email,password_hash,role,created_at) VALUES(?,?,?,?,?,?)').run('existing-admin', 'Existing Admin', 'admin@preserve.test', hash, 'Admin', '2026-01-01');
  db.prepare('INSERT INTO innovations(id,owner_id,code,title,kind,status,updated_at) VALUES(?,?,?,?,?,?,?)').run('manual-work', 'existing-admin', 'MANUAL-1', 'User-created work', 'Hak Cipta', 'Draft', '2026-01-01');
  db.close();
  const options = { dbPath, outputPath, backupRoot: join(dir, 'backups'), archiveOriginals: false };
  const result = await seedDemo(options);
  db = new DatabaseSync(dbPath);
  assert.equal(db.prepare("SELECT COUNT(*) AS n FROM innovations WHERE source_id LIKE 'sapatri-demo:%'").get().n, 36);
  assert.equal(db.prepare("SELECT COUNT(*) AS n FROM innovations WHERE source_id IS NOT NULL AND source_id NOT LIKE 'sapatri-demo:%'").get().n, 0);
  assert.equal(db.prepare("SELECT password_hash FROM users WHERE id='existing-admin'").get().password_hash, hash);
  assert.equal(db.prepare("SELECT title FROM innovations WHERE id='manual-work'").get().title, 'User-created work');
  assert.equal(db.prepare('SELECT COUNT(*) AS n FROM aftercare').get().n, 12);
  assert.equal(db.prepare('PRAGMA foreign_key_check').all().length, 0);
  const backup = new DatabaseSync(join(result.backupDir, 'sapatri.sqlite'), { readOnly: true });
  assert.equal(backup.prepare("SELECT title FROM innovations WHERE id='manual-work'").get().title, 'User-created work');
  backup.close();
  const publicData = JSON.parse(readFileSync(outputPath));
  assert.equal(publicData.innovations.length, 36);
  assert.equal(new Set(publicData.innovations.flatMap(w => w.districts)).size, 12);
  assert.ok(!JSON.stringify(publicData).includes('example.test'));
  const care = db.prepare('SELECT a.data,i.kind FROM aftercare a JOIN innovations i ON i.id=a.innovation_id').all();
  for (const kind of ['Hak Cipta', 'Hak Terkait']) assert.equal(new Set(care.filter(c => c.kind === kind).map(c => JSON.parse(c.data).participantType)).size, 3);
  db.close();
  await assert.rejects(seedDemo(options), /sudah tersedia/);
  await seedDemo({ ...options, replace: true });
  app = await createApplication({ dbPath, secureCookies: false });
  app.server.listen(0, '127.0.0.1'); await once(app.server, 'listening');
  const base = `http://127.0.0.1:${app.server.address().port}/api`;
  const credentials = JSON.parse(readFileSync(join(dir, 'demo-access.json'))).accounts[0];
  const login = await fetch(base + '/login', { method: 'POST', headers: { 'Content-Type': 'application/json' }, body: JSON.stringify(credentials) });
  assert.equal(login.status, 200);
  const session = await login.json();
  const headers = { Cookie: login.headers.get('set-cookie').split(';')[0], 'X-CSRF-Token': session.csrf, 'Content-Type': 'application/json' };
  const works = await fetch(base + '/innovations', { headers }).then(r => r.json());
  assert.ok(works.every(w => w.owner_id === session.user.id));
  const draft = works.find(w => w.status === 'Draft');
  assert.ok(draft);
  const submit = await fetch(base + `/innovations/${draft.id}/submit`, { method: 'POST', headers, body: '{}' });
  assert.equal(submit.status, 200, await submit.text());
  const pdf = await fetch(base + `/files/${draft.data.attachments[0].id}`, { headers });
  assert.equal(pdf.status, 200);
  assert.ok((await pdf.text()).includes('BUKAN DOKUMEN RESMI'));
  assert.equal((await fetch(base + `/files/${draft.data.attachments[0].id}`)).status, 401);
  const landing = await fetch(base + '/landing').then(r => r.json());
  assert.equal(landing.slides.length, 3);
  for (const s of landing.slides) assert.equal((await fetch(base + `/files/${s.imageId}`)).status, 200);
});
