CREATE SCHEMA IF NOT EXISTS sapatri;
REVOKE ALL ON SCHEMA sapatri FROM PUBLIC;
SET LOCAL search_path TO sapatri, pg_catalog;

CREATE TABLE IF NOT EXISTS regions(id TEXT PRIMARY KEY, level TEXT NOT NULL, parent_id TEXT REFERENCES regions(id), code TEXT UNIQUE NOT NULL, name TEXT NOT NULL, active INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS users(id TEXT PRIMARY KEY, name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, password_hash TEXT NOT NULL, role TEXT NOT NULL CHECK(role IN ('Admin','User')), active INTEGER NOT NULL DEFAULT 1, phone TEXT NOT NULL DEFAULT '', district_id TEXT REFERENCES regions(id), village_id TEXT REFERENCES regions(id), photo_id TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS sessions(hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, csrf TEXT NOT NULL, expires BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS resets(hash TEXT PRIMARY KEY, user_id TEXT NOT NULL REFERENCES users(id) ON DELETE CASCADE, expires BIGINT NOT NULL);
CREATE TABLE IF NOT EXISTS innovations(id TEXT PRIMARY KEY, owner_id TEXT REFERENCES users(id), code TEXT UNIQUE NOT NULL, title TEXT NOT NULL DEFAULT '', kind TEXT NOT NULL DEFAULT 'Hak Cipta', status TEXT, created_at TEXT, submitted_at TEXT, updated_at TEXT NOT NULL, source_id TEXT UNIQUE, data TEXT NOT NULL DEFAULT '{}', version INTEGER NOT NULL DEFAULT 1);
CREATE TABLE IF NOT EXISTS files(id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES users(id), innovation_id TEXT REFERENCES innovations(id) ON DELETE CASCADE, purpose TEXT NOT NULL, name TEXT NOT NULL, mime TEXT NOT NULL, bytes BYTEA NOT NULL, storage_path TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS aftercare(id TEXT PRIMARY KEY, innovation_id TEXT NOT NULL REFERENCES innovations(id), data TEXT NOT NULL, updated_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS content(key TEXT PRIMARY KEY, data TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS audit(id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, actor_id TEXT, action TEXT NOT NULL, record_id TEXT, created_at TEXT NOT NULL);
CREATE TABLE IF NOT EXISTS pending_uploads(id TEXT PRIMARY KEY, owner_id TEXT NOT NULL REFERENCES users(id), innovation_id TEXT REFERENCES innovations(id) ON DELETE CASCADE, purpose TEXT NOT NULL, name TEXT NOT NULL, path TEXT NOT NULL UNIQUE, expires BIGINT NOT NULL, file_id TEXT);
CREATE TABLE IF NOT EXISTS rate_limits(key TEXT PRIMARY KEY, attempts INTEGER NOT NULL, expires BIGINT NOT NULL);
CREATE INDEX IF NOT EXISTS innovations_owner ON innovations(owner_id);
CREATE INDEX IF NOT EXISTS files_innovation ON files(innovation_id);
CREATE INDEX IF NOT EXISTS aftercare_innovation ON aftercare(innovation_id);
CREATE INDEX IF NOT EXISTS sessions_user ON sessions(user_id);
CREATE INDEX IF NOT EXISTS pending_owner ON pending_uploads(owner_id);
CREATE INDEX IF NOT EXISTS pending_expires ON pending_uploads(expires);
CREATE INDEX IF NOT EXISTS rate_limits_expires ON rate_limits(expires);

-- Custom login remains in Node.js. These tables are deliberately outside the
-- Data API's public schema, with no browser role grants or public RLS policies.
DO $$
DECLARE t TEXT;
BEGIN
  FOREACH t IN ARRAY ARRAY['regions','users','sessions','resets','innovations','files','aftercare','content','audit','pending_uploads','rate_limits'] LOOP
    EXECUTE format('ALTER TABLE sapatri.%I ENABLE ROW LEVEL SECURITY', t);
    EXECUTE format('REVOKE ALL ON TABLE sapatri.%I FROM PUBLIC', t);
  END LOOP;
  IF EXISTS (SELECT FROM pg_roles WHERE rolname='anon') THEN
    REVOKE ALL ON SCHEMA sapatri FROM anon;
    REVOKE ALL ON ALL TABLES IN SCHEMA sapatri FROM anon;
  END IF;
  IF EXISTS (SELECT FROM pg_roles WHERE rolname='authenticated') THEN
    REVOKE ALL ON SCHEMA sapatri FROM authenticated;
    REVOKE ALL ON ALL TABLES IN SCHEMA sapatri FROM authenticated;
  END IF;
END $$;
